#
# This file is automatically generated, do not edit it manually.
#
# The following command was used to generate this file:
#   bin/update_terraform_environment_subdir.py test kubernetes 
#
terraform {
  backend "azurerm" {
    resource_group_name = "uumpatest-default"
    storage_account_name = "uumpatestsecureblobs"
    container_name = "uumpatest-secure-blobs"
    key = "terraform.tfstate.kubernetes"
  }
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=3.32.0"
    }
    azuread = {
      source  = "hashicorp/azuread"
      version = "=2.30.0"
    }
    azuredevops = {
      source = "microsoft/azuredevops"
      version = "=0.3.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "=2.16.0"
    }
  }
}

provider "azurerm" {
  subscription_id = "db3fac17-7311-43b7-9e53-707ff92b44c7"
  features {}
}
provider "azuread" {
  tenant_id = "f07e8778-d89e-4bca-9cd6-e1ffb6ed9b0e"
}
provider "kubernetes" {
  config_path = "~/.kube/config"
  config_context = "uumpatest"
}

locals {
    name_prefix = "uumpatest"
    location = "West Europe"
}

module "kubernetes" {
  source = "../../../modules/kubernetes"
  location = local.location
  name_prefix = local.name_prefix
  core_resources = data.terraform_remote_state.core.outputs.core_resources
  dns = data.terraform_remote_state.dns.outputs.dns
}

output "argocd_integration_username" {
  value = module.kubernetes.argocd_integration_username
}

output "argocd_integration_password_secret_name" {
  value = module.kubernetes.argocd_integration_password_secret_name
}

output "kubernetes" {
  value = module.kubernetes.kubernetes
}

data "terraform_remote_state" "core" {
    backend = "azurerm"
    config = {
        resource_group_name = "uumpatest-default"
        storage_account_name = "uumpatestsecureblobs"
        container_name = "uumpatest-secure-blobs"
        key = "terraform.tfstate.core"
    }
}
data "terraform_remote_state" "dns" {
    backend = "azurerm"
    config = {
        resource_group_name = "uumpatest-default"
        storage_account_name = "uumpatestsecureblobs"
        container_name = "uumpatest-secure-blobs"
        key = "terraform.tfstate.dns"
    }
}
