#
# This file is automatically generated, do not edit it manually.
#
# The following command was used to generate this file:
#   bin/update_terraform_environment_subdir.py test dns 
#
terraform {
  backend "azurerm" {
    resource_group_name = "uumpatest-default"
    storage_account_name = "uumpatestsecureblobs"
    container_name = "uumpatest-secure-blobs"
    key = "terraform.tfstate.dns"
  }
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=3.32.0"
    }
    azuread = {
      source  = "hashicorp/azuread"
      version = "=2.30.0"
    }

  }
}

provider "azurerm" {
  subscription_id = "db3fac17-7311-43b7-9e53-707ff92b44c7"
  features {}
}
provider "azuread" {
  tenant_id = "f07e8778-d89e-4bca-9cd6-e1ffb6ed9b0e"
}

locals {
    name_prefix = "uumpatest"
    location = "West Europe"
}

module "dns" {
  source = "../../../modules/dns"
  location = local.location
  name_prefix = local.name_prefix
  core_resources = data.terraform_remote_state.core.outputs.core_resources
}

output "dns" {
    value = module.dns.dns
}

data "terraform_remote_state" "core" {
    backend = "azurerm"
    config = {
        resource_group_name = "uumpatest-default"
        storage_account_name = "uumpatestsecureblobs"
        container_name = "uumpatest-secure-blobs"
        key = "terraform.tfstate.core"
    }
}
