kube-prometheus-stack:

  grafana:
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - "grafana.~iac:uumpa_root_domain~"
    persistence:
      enabled: true

  prometheus:
    prometheusSpec:
      retention: 5d
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 100Gi

  kubeControllerManager:
    enabled: false

  kubeScheduler:
    enabled: false

  kubeProxy:
    enabled: false

  defaultRules:
    create: true
    rules:
      kubeControllerManager: false
      kubeProxy: false
      kubeScheduler: false
