apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: gamal-cert
spec:
  provider: azure
  parameters:
    clientID: "~iac:secrets_provider_client_id~"
    tenantID: "~iac:tenant_id~"
    keyvaultName: "~iac:keyvault_name~"
    objects: |
      array:
        - |
          objectName: "~iac:gamal_wildcard_pfx_secret_name~"
          objectType: secret
  secretObjects:
    - secretName: gamal-cert
      type: kubernetes.io/tls
      data:
        - objectName: "~iac:gamal_wildcard_pfx_secret_name~"
          key: tls.key
        - objectName: "~iac:gamal_wildcard_pfx_secret_name~"
          key: tls.crt
