projects:

  - name: infra
    spec:
      clusterResourceWhitelist:
        - group: '*'
          kind: '*'
      destinations:
        - name: '*'
          namespace: cluster-admin
          server: 'https://kubernetes.default.svc'
        - name: '*'
          namespace: ingress-nginx
          server: 'https://kubernetes.default.svc'
      sourceRepos:
        - https://uumpa@dev.azure.com/uumpa/uumpa/_git/uumpa-iac
