apps:

  - name: gamal
    disableAutoSync: false
    project: gamal
    destinationNamespace: gamal
    source:
      repoURL: https://uumpa@dev.azure.com/uumpa/uumpa/_git/uumpa-iac
      targetRevision: main
      path: apps/gamal
    sourceVaultPluginHelmValueFiles:
      - values.yaml

  - name: sonarqube
    disableAutoSync: true
    project: sonarqube
    destinationNamespace: sonarqube
    source:
      repoURL: https://uumpa@dev.azure.com/uumpa/uumpa/_git/uumpa-iac
      targetRevision: main
      path: apps/sonarqube
    sourceVaultPluginHelmValueFiles:
      - values.yaml

  - name: roborotman
    disableAutoSync: true
    project: roborotman
    destinationNamespace: roborotman
    source:
      repoURL: https://uumpa@dev.azure.com/uumpa/uumpa/_git/uumpa-iac
      targetRevision: main
      path: apps/roborotman
    sourceVaultPluginHelmValueFiles:
      - values.yaml
