apps:

  - name: gamal
    disableAutoSync: false
    project: gamal
    destinationNamespace: gamal
    source:
      repoURL: https://uumpa@dev.azure.com/uumpa/uumpa/_git/uumpa-iac
      targetRevision: main
      path: apps/gamal
    sourceVaultPluginHelmValueFiles:
      - values.yaml

  - name: sonarqube
    disableAutoSync: true
    project: sonarqube
    destinationNamespace: sonarqube
    source:
      repoURL: https://uumpa@dev.azure.com/uumpa/uumpa/_git/uumpa-iac
      targetRevision: main
      path: apps/sonarqube
    sourceVaultPluginHelmValueFiles:
      - values.yaml
    sourceVaultPluginExtraHelmArgs:
      - --api-versions=monitoring.coreos.com/v1/ServiceMonitor
      - --api-versions=monitoring.coreos.com/v1/PrometheusRule
      -
