projects:

  - name: infra
    spec:
      clusterResourceWhitelist:
        - group: '*'
          kind: '*'
      destinations:
        - name: '*'
          namespace: cluster-admin
          server: 'https://kubernetes.default.svc'
        - name: '*'
          namespace: ingress-nginx
          server: 'https://kubernetes.default.svc'
        - name: '*'
          namespace: monitoring
          server: 'https://kubernetes.default.svc'
        - name: '*'
          namespace: kube-system
          server: 'https://kubernetes.default.svc'
        - name: '*'
          namespace: logging
          server: 'https://kubernetes.default.svc'
      sourceRepos:
        - https://uumpa@dev.azure.com/uumpa/uumpa/_git/uumpa-iac
        - https://github.com/prometheus-community/helm-charts.git
        - https://github.com/grafana/helm-charts.git

  - name: gamal
    spec:
      clusterResourceWhitelist:
        - group: '*'
          kind: '*'
      destinations:
        - name: '*'
          namespace: gamal
          server: 'https://kubernetes.default.svc'
      sourceRepos:
        - https://uumpa@dev.azure.com/uumpa/uumpa/_git/uumpa-iac

  - name: sonarqube
    spec:
      clusterResourceWhitelist:
        - group: '*'
          kind: '*'
      destinations:
        - name: '*'
          namespace: sonarqube
          server: 'https://kubernetes.default.svc'
      sourceRepos:
        - https://uumpa@dev.azure.com/uumpa/uumpa/_git/uumpa-iac

  - name: roborotman
    spec:
      clusterResourceWhitelist:
        - group: '*'
          kind: '*'
      destinations:
        - name: '*'
          namespace: roborotman
          server: 'https://kubernetes.default.svc'
      sourceRepos:
        - https://uumpa@dev.azure.com/uumpa/uumpa/_git/uumpa-iac
