apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- install.yaml

patchesStrategicMerge:
- ingress-nginx-controller-deployment.yaml
- ingress-nginx-controller-configmap.yaml
