ingress:
  host: "roborotman.~iac:uumpa_root_domain~"

web:
  image: ghcr.io/orihoch/chatgptgames/rotman:c381eab31a67f84b2004f963fc1ab337f4755fab
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 200Mi

nginx:
  image: ghcr.io/orihoch/chatgptgames/rotman-nginx:c381eab31a67f84b2004f963fc1ab337f4755fab
  resources:
    requests:
      cpu: 25m
      memory: 50Mi
    limits:
      cpu: 50m
      memory: 100Mi
