ingress:
  host: "roborotman.~iac:uumpa_root_domain~"

web:
  image: ghcr.io/orihoch/chatgptgames/rotman:676dcb375ac9438cfc963973dd91f2116978a0b3
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 200Mi

nginx:
  image: ghcr.io/orihoch/chatgptgames/rotman-nginx:676dcb375ac9438cfc963973dd91f2116978a0b3
  resources:
    requests:
      cpu: 25m
      memory: 50Mi
    limits:
      cpu: 50m
      memory: 100Mi
