ingress:
  host: "roborotman.~iac:uumpa_root_domain~"

web:
  image: ghcr.io/orihoch/chatgptgames/rotman:80961fbd538bcf748bdafdad0dbe3a270487b892
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 200Mi

nginx:
  image: ghcr.io/orihoch/chatgptgames/rotman-nginx:80961fbd538bcf748bdafdad0dbe3a270487b892
  resources:
    requests:
      cpu: 25m
      memory: 50Mi
    limits:
      cpu: 50m
      memory: 100Mi
