sonarqube:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - name: "sonarqube.~iac:uumpa_root_domain~"
        path: /

  persistence:
    enabled: true
    storageClass: managed-csi
    size: 10Gi

  postgresql:
    persistence:
      storageClass: managed-csi
      size: 20Gi
