apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: roborotman
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
        - path: /static
          backend:
            serviceName: nginx
            servicePort: 80
        - path: /
          backend:
            serviceName: web
            servicePort: 80
