apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      terminationGracePeriodSeconds: 2
      containers:
      - name: nginx
        image: {{ .Values.nginx.image | quote }}
        resources: {{ toYaml .Values.nginx.resources | nindent 10 }}
