trigger:
  branches:
    include:
      - main
  paths:
    include:
      - apps/argocd/plugin/*
      - azure_pipelines/argocd_plugin_build.yml

pool:
  vmImage: ubuntu-latest

variables:
- group: "uumpa devops"

steps:
- task: AzureCLI@2
  env:
    ACR_REGISTRY_NAME: "$(container_registry_name)"
    ACR_REGISTRY_LOGIN_SERVER: "$(container_registry_login_server)"
    APPCONFIG_NAME: "$(appconfig_name)"
    AKS_RESOURCE_GROUP_NAME: "$(resource_group_name)"
    AKS_CLUSTER_NAME: "$(aks_cluster_name)"
  inputs:
    azureSubscription: 'uumpa service connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      curl -sLo kubelogin.zip https://github.com/Azure/kubelogin/releases/download/v0.0.24/kubelogin-linux-amd64.zip &&\
      sudo unzip -j kubelogin.zip -d /usr/local/bin &&\
      python3 azure_pipelines/build_push_deploy_latest.py \
        --image-name "argocd-plugin" \
        --image-tag "$(Build.SourceVersion)" \
        --docker-path apps/argocd/plugin \
        --appconfig-key argocd-plugin-latest-image \
        --kubectl-patch-json '{"namespace": "argocd", "name": "argocd-repo-server", "container_name": "argocd-repo-server"}'
