trigger:
  branches:
    include:
      - main
  paths:
    include:
      - dns/*
      - azure_pipelines/dns_certbot_build.yml

pool:
  vmImage: ubuntu-latest

variables:
- group: "uumpa devops"
- group: "argocd sync"

steps:
- task: AzureCLI@2
  env:
    ACR_REGISTRY_NAME: "$(container_registry_name)"
    ACR_REGISTRY_LOGIN_SERVER: "$(container_registry_login_server)"
    APPCONFIG_NAME: "$(appconfig_name)"
    ARGOCD_TOKEN: "$(argocd-syncer-user-token)"
    ARGOCD_DOMAIN: "$(argocd-domain)"
  inputs:
    azureSubscription: 'uumpa service connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      python3 azure_pipelines/build_push_deploy_latest.py \
        --image-name "dns-certbot" \
        --image-tag "$(Build.SourceVersion)" \
        --docker-path dns \
        --appconfig-key dns-certbot-latest-image \
        --argocd-application-name cluster-admin
