trigger:
  branches:
    include:
      - main
  paths:
    include:
      - dns/*
      - azure_pipelines/dns_certbot_build.yml

pool:
  vmImage: ubuntu-latest

variables:
- group: "uumpa devops"
- group: "argocd sync"

steps:
- task: AzureCLI@2
  env:
    REGISTRY: "$(container_registry_name)"
    IMAGE_NAME: "$(container_registry_login_server)/dns-certbot"
    IMAGE_TAG: "$(Build.SourceVersion)"
    APPCONFIG: "$(appconfig_name)"
    ARGOCD_TOKEN: "$(argocd-syncer-user-token)"
    ARGOCD_DOMAIN: "$(argocd-domain)"
    ARGOCD_APPLICATION_NAME: cluster-admin
  inputs:
    azureSubscription: 'uumpa service connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az acr login --name $REGISTRY &&\
      if docker pull "${IMAGE_NAME}:latest"; then
        CACHE_FROM="--cache-from ${IMAGE_NAME}:latest"
      fi &&\
      docker build -t "${IMAGE_NAME}:${IMAGE_TAG}" $CACHE_FROM dns &&\
      docker push "${IMAGE_NAME}:${IMAGE_TAG}" &&\
      az appconfig kv set -y --name $APPCONFIG --key dns-certbot-latest-image --value "${IMAGE_NAME}:${IMAGE_TAG}" &&\
      docker tag "${IMAGE_NAME}:${IMAGE_TAG}" "${IMAGE_NAME}:latest" &&\
      docker push "${IMAGE_NAME}:latest" &&\
      curl -H "Authorization: Bearer ${ARGOCD_TOKEN}" \
        "https://${ARGOCD_DOMAIN}/api/v1/applications/${ARGOCD_APPLICATION_NAME}?refresh=hard"
