loki:
  loki:
    auth_enabled: false
  monitoring:
    dashboards:
      namespace: monitoring
      labels:
        grafana_dashboard: "1"
        release: monitoring
    rules:
      namespace: monitoring
      labels:
        release: monitoring
    serviceMonitor:
      namespace: monitoring
      labels:
          release: monitoring
      namespaceSelector:
        matchNames:
          - logging
      metricsInstance:
        enabled: false
    selfMonitoring:
      enabled: false
    lokiCanary:
      enabled: false
  test:
    enabled: false

  storage:
    bucketNames:
      chunks: chunks
      ruler: ruler
      admin: admin
    type: azure
    azure:
      accountName: "~iac:logs_storage_account_name~"
      accountKey: "~iac:logs_storage_account_key~"
#      useManagedIdentity: false
#      userAssignedId: null
#      requestTimeout: null
