loki:
  monitoring:
    dashboards:
      namespace: monitoring

  storage:
    bucketNames:
      chunks: chunks
      ruler: ruler
      admin: admin
    type: azure
    azure:
      accountName: "~iac:logs_storage_account_name~"
      accountKey: "~iac:logs_storage_account_key~"
#      useManagedIdentity: false
#      userAssignedId: null
#      requestTimeout: null
