apiVersion: batch/v1
kind: CronJob
metadata:
  name: certbot
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      completions: 1
      backoffLimit: 0
      template:
        spec:
          serviceAccountName: certbot
          restartPolicy: Never
          containers:
            - name: certbot
              image: "~iac:dns_certbot_docker_image~"
              command:
              - bash
              - -c
              - |
                az login --tenant $TENANT_ID --service-principal --password "${SP_PASSWORD}" --username $SP_USERNAME &&\
                uumpa-certbot.py uumpa uumpa-wildcard-pfx "${UUMPA_ROOT_DOMAIN}" "${ADMIN_EMAIL}" --in-cluster
              env:
                - name: SP_USERNAME
                  value: "~iac:certbot_service_principal_app_id~"
                - name: TENANT_ID
                  value: "~iac:tenant_id~"
                - name: SP_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: certbot
                      key: sp_password
                - name: UUMPA_ROOT_DOMAIN
                  value: "~iac:uumpa_root_domain~"
                - name: ADMIN_EMAIL
                  value: "~iac:admin_email~"
              volumeMounts:
                - name: secrets-store-inline
                  mountPath: "/mnt/secrets-store"
                  readOnly: true
          volumes:
            - name: secrets-store-inline
              csi:
                driver: secrets-store.csi.k8s.io
                readOnly: true
                volumeAttributes:
                  secretProviderClass: "certbot"
