apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: certbot
spec:
  provider: azure
  parameters:
    clientID: "~iac:secrets_provider_client_id~"
    tenantID: "~iac:tenant_id~"
    keyvaultName: "~iac:keyvault_name~"
    objects: |
      array:
        - |
          objectName: "~iac:certbot_service_principal_password_secret_name~"
          objectType: secret
  secretObjects:
    - secretName: certbot
      type: Opaque
      data:
        - objectName: "~iac:certbot_service_principal_password_secret_name~"
          key: sp_password
