apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: certbot
spec:
  provider: azure
  parameters:
    clientID: "~iac:secrets_provider_client_id~"
    tenantID: "~iac:tenant_id~"
    keyvaultName: "uumpa"
    objects: |
      array:
        - |
          objectName: "uumpa-iac-sp-certbot-password"
          objectType: secret
  secretObjects:
    - secretName: certbot
      type: Opaque
      data:
        - objectName: uumpa-iac-sp-certbot-password
          key: sp_password
